---
title: "Deanna Stover's Courses"
url: "https://github.com/deanna-stover"
baseurl: "/coursesCNU"
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Readme.md
  - _scripts/

theme: jekyll-theme-minimal
logo: /images/PenNib.png
